# Generated by Django 5.2.17 on 2026-10-02 17:53

import apps.cms.models
import apps.media.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[apps.media.validators.validate_plain_text])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, validators=[apps.media.validators.validate_plain_text])),
                ('seo_description', models.CharField(blank=True, max_length=300, validators=[apps.media.validators.validate_multiline_plain_text])),
                ('canonical_url', models.CharField(blank=True, max_length=500, validators=[apps.cms.models.validate_canonical_url])),
                ('noindex', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.mediaasset')),
            ],
            options={
                'ordering': ['slug'],
                'permissions': [('publish_page', 'Can publish, unpublish or archive pages')],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('services', 'Services'), ('projects', 'Projects'), ('gallery', 'Gallery'), ('text-media', 'Text + media'), ('stats', 'Stats'), ('certifications', 'Certifications'), ('cta', 'Call to action'), ('contact', 'Contact'), ('territory', 'Territory')], max_length=32)),
                ('variant', models.CharField(max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
            ],
            options={
                'ordering': ['page', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('page', 'position'), name='cms_pagesection_unique_position')],
            },
        ),
    ]
