# Generated by Django 5.2.17 on 2026-10-02 18:00

import apps.cms.models
import apps.media.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g. header, footer', unique=True)),
                ('title', models.CharField(max_length=100, validators=[apps.media.validators.validate_plain_text])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, validators=[apps.media.validators.validate_plain_text])),
                ('url', models.CharField(blank=True, max_length=500, validators=[apps.cms.models.validate_safe_url])),
                ('position', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cms.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.navigationmenu')),
            ],
            options={
                'ordering': ['menu', 'position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('page__isnull', False), ('url', '')), models.Q(('page__isnull', True), models.Q(('url', ''), _negated=True)), _connector='OR'), name='cms_navigationitem_single_target', violation_error_message='Choose exactly one target: a page or a URL.')],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_title', models.CharField(blank=True, max_length=70, validators=[apps.media.validators.validate_plain_text])),
                ('default_description', models.CharField(blank=True, max_length=300, validators=[apps.media.validators.validate_multiline_plain_text])),
                ('allow_indexing', models.BooleanField(default=False, help_text='Off until launch: public pages are served with noindex.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'SEO settings',
                'verbose_name_plural': 'SEO settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='cms_seosettings_singleton')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200, validators=[apps.media.validators.validate_plain_text])),
                ('brand_name', models.CharField(blank=True, max_length=100, validators=[apps.media.validators.validate_plain_text])),
                ('vat_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^(IT)?\\d{11}$', 'Enter an 11-digit Italian VAT number (optionally prefixed by IT).')])),
                ('address', models.CharField(blank=True, max_length=300, validators=[apps.media.validators.validate_plain_text])),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ]{6,20}$', 'Enter digits, spaces and optional +.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=300, validators=[apps.media.validators.validate_multiline_plain_text])),
                ('tagline', models.CharField(blank=True, max_length=200, validators=[apps.media.validators.validate_plain_text])),
                ('certifications_text', models.CharField(blank=True, max_length=500, validators=[apps.media.validators.validate_multiline_plain_text])),
                ('primary_cta_label', models.CharField(blank=True, max_length=40, validators=[apps.media.validators.validate_plain_text])),
                ('primary_cta_url', models.CharField(blank=True, max_length=500, validators=[apps.cms.models.validate_safe_url])),
                ('footer_text', models.CharField(blank=True, max_length=1000, validators=[apps.media.validators.validate_multiline_plain_text])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cms.page')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='cms_sitesettings_singleton')],
            },
        ),
    ]
