# Generated by Django 5.2.17 on 2026-10-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_password_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('assign_role', 'Can assign RBAC roles to staff accounts'), ('deactivate_user', 'Can deactivate staff accounts'), ('manage_user_security', "Can manage other staff members' sessions and MFA")], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
