# Generated by Django 5.2.17 on 2026-10-02 17:47

import apps.media.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=100)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video')], editable=False, max_length=16)),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('checksum_sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, validators=[apps.media.validators.validate_plain_text])),
                ('caption', models.CharField(blank=True, max_length=500, validators=[apps.media.validators.validate_multiline_plain_text])),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=16)),
                ('origin', models.CharField(choices=[('STAFF_UPLOAD', 'Uploaded by staff'), ('CLIENT_PROVIDED', 'Provided by the client'), ('THIRD_PARTY', 'Third party / licensed')], default='STAFF_UPLOAD', max_length=32)),
                ('source_note', models.CharField(blank=True, help_text='Author, licence or provenance of the file.', max_length=255, validators=[apps.media.validators.validate_plain_text])),
                ('authorization_status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved for publication'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Public site usage requires APPROVED (photo publication rules are DA DEFINIRE).', max_length=16)),
                ('stored_publicly', models.BooleanField(default=False, editable=False, help_text='True while the blob sits in the public storage (PUBLIC and APPROVED).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('approve_mediaasset', 'Can approve or reject media assets for public use'), ('download_private_mediaasset', 'Can download private media assets')],
            },
        ),
    ]
