# Generated by Django 5.2.17 on 2026-10-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=16)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx')],
            },
        ),
        # Append-only at the database level: reject UPDATE and DELETE on audit rows.
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION audit_reject_mutation() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'audit_auditevent is append-only';
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER audit_auditevent_append_only
                    BEFORE UPDATE OR DELETE ON audit_auditevent
                    FOR EACH ROW EXECUTE FUNCTION audit_reject_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS audit_auditevent_append_only ON audit_auditevent;
                DROP FUNCTION IF EXISTS audit_reject_mutation();
            """,
        ),
    ]
